[WIP] Added default LogStore implementation for the .gs scheme
delta-io/delta pull request #1071
Opened 2022-04-14 20:05 UTC by ahlag

## Description
Adds gs scheme to default LogStore implementation

## How was this patch tested?
Unit Test

## Does this PR introduce _any_ user-facing changes?
Yes, users can automatically derive the GCS log store conf based on the path

2022-04-14 22:52 UTC, tdas commented
@ahlag  thank you for doing this. this looks good to me, but have you tested this out using an actual GCS path and without the conf needed earlier?

2022-04-15 00:51 UTC, ahlag commented
@marmbrus 
Hi, thank you for reaching out. 
@vkorukanti said he will test it out because he has a local GCP setup.

2022-04-18 22:20 UTC, vkorukanti commented
Tested locally with [debug logging statements](https://github.com/vkorukanti/delta/commit/5f4f3fce7c27b1b788bba0bdbe21ab0936329859) added in GCSLogStore impl.

## Before the fix
### Without explicit GCSLogStore conf
```
(base) % bin/spark-shell --packages io.delta:delta-core_2.12:1.3.0-SNAPSHOT \ 
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"

scala> spark.read.format("delta").load("gs://delta120-test-bucket/delta_temp").show()
22/04/18 14:43:08 WARN GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://delta120-test-bucket/'
+---+
| id|
+---+
|  5|
|  6|
|  5|
....
+---+

scala> spark.range(5, 10).write.format("delta").mode("append").save("gs://delta120-test-bucket/delta_temp")
22/04/18 14:45:40 ERROR HDFSLogStore: The error typically occurs when the default LogStore implementation, that
is, HDFSLogStore, is used to write into a Delta table on a non-HDFS storage system.
In order to get the transactional ACID guarantees on table updates, you have to use the
correct implementation of LogStore that is appropriate for your storage system.
See https://docs.delta.io/latest/delta-storage.html for details.
org.apache.hadoop.fs.UnsupportedFileSystemException: fs.AbstractFileSystem.gs.impl=null: No AbstractFileSystem configured for scheme: gs. <-------- ADDITIONAL CONFIRMATION THAT GCSLogStore IS NOT USED
```
### With explicit GCSLogStore conf
```
base) % bin/spark-shell --packages io.delta:delta-core_2.12:1.3.0-SNAPSHOT \
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" \
--conf "spark.delta.logStore.gs.impl=io.delta.storage.GCSLogStore"

scala> spark.read.format("delta").load("gs://delta120-test-bucket/delta_temp").show()
22/04/18 14:41:56 WARN GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://delta120-test-bucket/'
22/04/18 14:41:57 ERROR GCSLogStore: DO NOT LAND: Inited GCSLogStore  <---------- DEBUG LOGGING
+---+
| id|
+---+
|  5|
|  6|
...
+---+

scala> spark.range(5, 10).write.format("delta").mode("append").save("gs://delta120-test-bucket/delta_temp")
22/04/18 14:47:16 WARN GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://delta120-test-bucket/'
22/04/18 14:47:16 ERROR GCSLogStore: DO NOT LAND: Inited GCSLogStore <---------- DEBUG LOGGING
22/04/18 14:47:26 ERROR GCSLogStore: DO NOT LAND: Using GCSLogStore.write  <---------- DEBUG LOGGING

```

## After the fix
### Without explicit GCSLogStore conf
```
(base) % bin/spark-shell --packages io.delta:delta-core_2.12:1.3.0-SNAPSHOT \
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"

scala> spark.range(5, 10).write.format("delta").mode("append").save("gs://delta120-test-bucket/delta_temp")
22/04/18 15:07:44 WARN GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://delta120-test-bucket/'
22/04/18 15:07:44 ERROR GCSLogStore: DO NOT LAND: Inited GCSLogStore  <---------- DEBUG LOGGING
22/04/18 15:07:54 ERROR GCSLogStore: DO NOT LAND: Using GCSLogStore.write  <---------- DEBUG LOGGING

scala> spark.read.format("delta").load("gs://delta120-test-bucket/delta_temp").show()
+---+
| id|
+---+
|  8|
|  9|
|  5|
....

```
### With explicit GCSLogStoreConf
```
(base) % bin/spark-shell --packages io.delta:delta-core_2.12:1.3.0-SNAPSHOT \
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" \
--conf "spark.delta.logStore.gs.impl=io.delta.storage.GCSLogStore"

scala> spark.read.format("delta").load("gs://delta120-test-bucket/delta_temp").show()
22/04/18 15:09:08 WARN GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://delta120-test-bucket/'
22/04/18 15:09:09 ERROR GCSLogStore: DO NOT LAND: Inited GCSLogStore  <---------- DEBUG LOGGING
+---+
| id|
+---+
|  8|
|  9|
|  5|
....
+---+

scala> spark.range(5, 10).write.format("delta").mode("append").save("gs://delta120-test-bucket/delta_temp")
22/04/18 15:09:32 ERROR GCSLogStore: DO NOT LAND: Using GCSLogStore.write  <---------- DEBUG LOGGING
```

2022-04-18 22:21 UTC, vkorukanti approved these changes

2022-04-19 20:34 UTC, scottsand-db requested changes

2022-04-19 20:34 UTC, scottsand-db commented on core/src/test/scala/org/apache/spark/sql/delta/DelegatingLogStoreSuite.scala
> +    }
please update the test below "DelegatingLogStore resolution using customized scheme confs"".
- add `"io.delta.storage.GCSLogStore"` and `classOf[org.apache.spark.sql.delta.storage.GCSLogStore].getName,`

2022-04-26 18:32 UTC, closed without merging