chore: Python codebase refactor
delta-io/delta pull request #1193
Opened 2022-06-11 06:49 UTC by koconder

## Description

Light refactor of python codebase with best practice, strings are escaped and some minor code tweaks.

## How was this patch tested?

Locally tested using existing tests and codebase.

## Does this PR introduce _any_ user-facing changes?

No

2022-06-11 22:52 UTC, koconder commented
I have patched the broken flake8 PEP 8 codestyle errors in unit testing

2022-06-18 05:44 UTC, koconder commented
@allisonport-db @scottsand-db @tdas @vkorukanti mind reviewing this light refactoring PR?

2022-06-21 15:30 UTC, scottsand-db commented
Hi @koconder - thanks for the ping. Yup I will be taking a look at it, just a little busy right now working on the next release of Delta. Will get to this soon! Thanks!

2022-07-14 18:52 UTC, scottsand-db requested changes
LGTM with minor nits. @vkorukanti take a look?

2022-07-14 18:52 UTC, scottsand-db commented on examples/python/quickstart_sql_on_paths.py
> +
nit: delete empty line

2022-07-14 18:52 UTC, scottsand-db commented on examples/python/utilities.py
> +print(spark.sql('DESCRIBE HISTORY delta.`/tmp/delta-table`').collect())
nit: why the change from `"` to `'` ? you haven't done it so far in this PR?

2022-07-14 18:52 UTC, scottsand-db commented on python/delta/tables.py
> +                    ", found '%s' of type '%s" % (str(col), str(type(col)))
why not use `f"..."` and `{str(col)}` here, too?

2022-07-14 18:52 UTC, scottsand-db commented on python/delta/tables.py
> +                    "found '%s' of type '%s'" % (str(expr), str(type(expr)))
ditto

2022-07-17 23:08 UTC, koconder commented
@scottsand-db comments and issues resolved

2022-07-21 19:53 UTC, scottsand-db commented
@koconder - after discussing with another engineer @vkorukanti on my team, this PR is a little bit too big to review. Could you split this up into, say, 2 or 3 smaller PRs?

2022-07-21 19:58 UTC, vkorukanti commented
> @koconder - after discussing with another engineer @vkorukanti on my team, this PR is a little bit too big to review. Could you split this up into, say, 2 or 3 smaller PRs?

May be one file per PR? Sorry, it is more work, but helps with review and testing.

2022-08-10 03:07 UTC, scottsand-db commented
As mentioned above, we've asked that you kindly split up this PR into smaller PRs, as that will be easier to review. Closing this PR for now. Cheers.

2022-08-10 03:07 UTC, closed without merging