log first ioexception message
delta-io/delta pull request #1405
Opened 2022-10-02 10:10 UTC by amirmor1

## Description

Resolves https://github.com/delta-io/delta/issues/464

This PR simply logs error when the first IOException was throws during Vacuum operation.

## How was this patch tested?

Current unit tests. No additional tests created.

## Does this PR introduce _any_ user-facing changes?

No API changes, but a log message on the first IOException failure during Vacuum opperation

2022-10-04 20:17 UTC, scottsand-db requested changes

2022-10-04 20:17 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
> +      case e: IOException if tries == 1 =>
"first" doesn't mean `tries == 1`. This method is called recursively (ironic, given that it deletes non-recursively).
I will be called with tries = N, then N-1, then N-1, ...

So the only way to detect the "first" call is to duplicate the code to another method. The steps will be
a) call the public API `tryDeleteNonRecursive`. If it fails, this is the first attempt.
b) that method will have to call `_tryDeleteNonRecursive`, or some other **private** internal method helper

OR

Another thing we could do is add a default `first: Boolean = true` param to this public API, and then have all recursive calls set `first = false`.

Honestly none of these options seems great. @zsxwing any other ideas?

2022-12-02 19:50 UTC, scottsand-db requested changes
1 minor nit, then LGTM

2022-12-02 19:50 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
> +  def tryDeleteNonRecursive(fs: FileSystem, path: Path, tries: Int = 3,
nit: can you format this method like so
```scala
def tryDeleteNonRecursive(
    fs: FileSystem,
    path: Path,
    tries: Int = 3,
    firstCall: Boolean = true): Boolean = {
```

2022-12-21 18:25 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
> +      case ioException: IOException if firstCall =>
on second thought, why do we need this `if firstCall` check?

Wouldn't this achieve the same result? We don't recurse any more ...

And if we did recurse ... and on the 3rd try ... we DO see an IOException ... then we know that we have not ever received a previous IOException.

```scala
case _: IOException =>
  logError(s"Vacuum failed to delete ${path.toString}", ioException)
  false
```

2022-12-21 18:25 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
> +      case ioException: IOException if firstCall =>
@amirmor1

2023-02-09 01:14 UTC, scottsand-db requested changes

2023-02-09 01:14 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala
> +  def tryDeleteNonRecursive(
why this formatting change?

2026-07-27 17:32 UTC, foss-contributor commented
@amirmor1, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:14 UTC, closed without merging