Ceil function partition added
delta-io/delta pull request #1452
Opened 2022-10-24 20:16 UTC by sherlockbeard

## Description

Resolves #1443 
## How was this patch tested?

added test in OptimizeGeneratedColumnSuite

## Does this PR introduce _any_ user-facing changes?

2022-11-03 17:21 UTC, allisonport-db commented
Hi @sherlockbeard sorry for the delay, I will try to look at this later today

2022-11-04 00:53 UTC, allisonport-db requested changes
We want to support all data types supported for the [Ceil function](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L251) which also includes DecimalType and LongType

2023-01-15 00:10 UTC, sherlockbeard commented
cc @allisonport-db

2023-01-15 14:05 UTC, sherlockbeard commented
cc @allisonport-db

2023-01-25 18:57 UTC, allisonport-db commented on core/src/main/scala/org/apache/spark/sql/delta/optimizablePartitionExpressions.scala
> +import org.apache.spark.sql.types.{DateType, DoubleType, IntegerType, StringType, TimestampType, LongType, DecimalType}
Can you check if IntegerType or any other datatypes are implicitly cast?

2023-02-16 18:24 UTC, sherlockbeard commented on core/src/main/scala/org/apache/spark/sql/delta/optimizablePartitionExpressions.scala
> +import org.apache.spark.sql.types.{DateType, DoubleType, IntegerType, StringType, TimestampType, LongType, DecimalType}
sorry had mail sync off so missed this message .
corrected it.

2023-03-08 18:16 UTC, sherlockbeard commented on core/src/main/scala/org/apache/spark/sql/delta/optimizablePartitionExpressions.scala
> +import org.apache.spark.sql.types.{DateType, DoubleType, IntegerType, StringType, TimestampType, LongType, DecimalType}
i added IntegerType import in first commit . after that code was changed but forgot to take it out .

2023-03-15 20:44 UTC, sherlockbeard commented on core/src/main/scala/org/apache/spark/sql/delta/optimizablePartitionExpressions.scala
> +import org.apache.spark.sql.types.{DateType, DoubleType, IntegerType, StringType, TimestampType, LongType, DecimalType}
cc @allisonport-db

2024-02-03 17:44 UTC, Nestor10 commented
Hello, I was looking for a first issue in delta. Is there anything I could do to get this PR off the floor? This seems fairly complete.

2024-07-25 09:11 UTC, closed without merging