add metadata information to PROTOCOL.md
delta-io/delta pull request #1473
Opened 2022-11-02 07:23 UTC by k0tk267

## Description
I add metadata information to PROTOCOL.md because the link TODO is not available.

This PR is link to [#1250](https://github.com/delta-io/delta/issues/1250)

## How was this patch tested?
Did't do test. This PR is document only changes.

## Does this PR introduce _any_ user-facing changes?
No

2022-11-02 22:02 UTC, scottsand-db requested changes
Welcome to delta! Thanks for contributing!

Left some feedback. Thanks for helping us improve our docs and protocol!

Let me know if you have any questions.

2022-11-02 22:02 UTC, scottsand-db commented on PROTOCOL.md
> +Field Name | Description
You can give an example of what types of keys/values are stored in the metadata. which is just a map of String->JSON-encoded value.

For example, the Column Mapping section gives some examples. he physical name is stored as part of the column metadata with the key delta.columnMapping.physicalName. The column id is stored within the metadata with the key delta.columnMapping.id. The column mapping is governed by the table property delta.columnMapping.mode and can be one of none, id, and name.
```

Generated columns also gives an example. The metadata for a column in the table schema MAY contain the key delta.generationExpression.
```
The metadata for a column in the table schema MAY contain the key delta.generationExpression.
```
The physical name is stored as part of the column metadata with the key delta.columnMapping.physicalName. The column id is stored within the metadata with the key delta.columnMapping.id. The column mapping is governed by the table property delta.columnMapping.mode and can be one of none, id, and name.
```

2022-11-05 10:14 UTC, k0tk267 commented
I fix document, but don't have enough confidence to cover all metadata types.
So, please teach me when I miss something.
In addition, I tried to add examples like bellow.
```
{
  "type" : "struct",
  "fields" : [ {
    "name" : "asset",
    "type" : "string",
    "nullable" : true,
    "metadata" : {
      "delta.columnMapping.id": 1,
      "delta.columnMapping.physicalName": "col-b96921f0-2329-4cb3-8d79-184b2bdab23b"
      "delta.identity.allowExplicitInsert": true,
      "delta.invariants": "{\"expression\": { \"expression\": \"x > 3\"} }",
      "delta.generationExpression": "???"
      ""
    }
  }
}
```
However, I did't know the example of `delta.generationExpression`.
So, if I need to add these examples, please teach me the example of `delta.generationExpression` or the reference of this.

2022-11-29 18:51 UTC, tdas commented on PROTOCOL.md
> +delta.generationExpression| Alaways parsed as SQL expression. The more information is [Generated Columns](#generated-columns)
```suggestion
delta.generationExpression| Always parsed as SQL expression. The more information is [Generated Columns](#generated-columns)
```

2022-11-29 18:55 UTC, tdas commented on PROTOCOL.md
> +delta.columnMapping| This is to avoid any column naming restrictions, and to support the renaming and dropping of columns without having to rewrite all the data. The more information is [Column Mappi
```suggestion
delta.columnMapping.*| These keys are used to store information about the mapping between the logical column name to  the physical name. See [Column Mapping](#column-mapping) for details.
```

there are multiple metadata entries with that columnMapping prefix

2022-11-30 03:27 UTC, k0tk267 commented
@tdas 
Thank you for your review !
I checked and fixed it !

2022-11-30 20:30 UTC, tdas commented on PROTOCOL.md
> +delta.identity.xxx| This is for defining identity columns. The more information is [Identity Columns](#identity-columns)
super minor: make this consistent with the format of column mapping
```suggestion
delta.identity.*| These keys are for defining identity columns. See [Identity Columns](#identity-columns) for details.
```

2022-11-30 20:32 UTC, tdas commented on PROTOCOL.md
> +delta.generationExpression| Always parsed as SQL expression. The more information is [Generated Columns](#generated-columns)
```suggestion
delta.generationExpression| SQL expression string. See [Generated Columns](#generated-columns) for details.
```

2022-11-30 20:32 UTC, tdas requested changes
Overall thank you for improve the quality of the Delta protocol doc :)

2022-12-01 12:25 UTC, k0tk267 commented
I have only committed to your review ... 
I'm sorry to bother you.

2022-12-01 16:49 UTC, tdas approved these changes
LGTM. will merge.

2022-12-05 22:31 UTC, closed without merging