Update checkpoint schema description
delta-io/delta pull request #1682
Opened 2023-04-05 20:30 UTC by felipepessoto

## Description

Update checkpoint schema description to explicitly mention that readerFeatures and writerFeatures should only exist in supported versions.

## How was this patch tested?

N/A

## Does this PR introduce _any_ user-facing changes?

No

2023-05-01 00:43 UTC, felipepessoto commented
Gently ping @scottsand-db, and @vkorukanti who reviewed my previous protocol PR.

Do you think this change in the checkpoint makes sense? That information is in the Protocol section, but I'd like to ensure anybody implementing the checkpoint don't have doubts about it.

2023-05-04 18:55 UTC, allisonport-db commented
@xupefei Can you take a look at this? I'm not clear on what the Protocol action will look like for say a table on (1, 2) written by Delta 2.3.

2023-05-05 07:44 UTC, xupefei commented
Have to reject this PR because the modification is not correct. The **checkpoint schema** (not Delta Log JSON schema) is mapped from the Scala `Protocol` case class, therefore `readerFeatures` and `writerFeatures` will be in the checkpoint schema even if a table is not using table features, because the Delta Lake's `Protocol` case class have corresponding fields.

The only difference regarding the table protocol version is:
- when a table is not using table features: `readerFeatures` and `writerFeatures` in the checkpoint are both `null`.
- when a table is not using writer table features: `readerFeatures` in the checkpoint is `null`, and `writerFeatures` is not `null`.
- when a table is not using reader+writer table features: `readerFeatures` and `writerFeatures` in the checkpoint are both not `null`.

2023-05-05 07:47 UTC, xupefei commented
Btw, modifications of this PR are correct for JSON schema: `readerFeatures` and `writerFeatures` only exists in JSON when protocol versions are 3 and 7.

2023-05-05 07:48 UTC, xupefei requested changes
Have to reject. Sorry!

2023-05-05 15:26 UTC, felipepessoto commented
But in that case it wouldn’t make all existing writers (which don’t write the new null fields to checkpoint) incompatible to Delta spec?

2023-05-10 17:58 UTC, felipepessoto commented
@xupefei, just confirming if my point makes sense. Or should I abandon this PR?

2023-05-12 08:18 UTC, xupefei commented
Valid point... Agree that what I said is an implementation detail. I think we could update the protocol according to the following:

- If a table has `readerVersion` 3, then a writer must write checkpoints with a not-null `readerFeatures` in the schema.
- If a table has `writerVersion` 7, then a writer must write checkpoints with a not-null `writerFeatures` in the schema.
- If a table has neither of the above, then a writer may or may not write `readerVersion` and/or `writerFeatures` into the checkpoint schema. But if it does, their values must be `null`.

WDYT?

2023-05-12 08:37 UTC, felipepessoto commented
Perfect, are you sending another PR, or should I change mine?

2023-05-19 07:21 UTC, xupefei commented on PROTOCOL.md
> +- If a table has neither of the above, then a writer chooses whether to write readerFeatures and/or writerFeatures into the checkpoint schema. But if it does, their values must be null.
```suggestion
- If a table has Reader Version 3, then a writer must write checkpoints with a not-null `readerFeatures` in the schema.
- If a table has Writer Version 7, then a writer must write checkpoints with a not-null `writerFeatures` in the schema.
- If a table has neither of the above, then a writer chooses whether to write `readerFeatures` and/or `writerFeatures` into the checkpoint schema. But if it does, their values must be null.
```

2023-05-19 07:22 UTC, xupefei approved these changes
Left a suggestion to correct the markdown format.
Otherwise lgtm, thank you for the fix!

2023-05-19 07:48 UTC, felipepessoto commented
Thanks, done

2023-05-25 22:37 UTC, felipepessoto commented
@allisonport-db is it you who can help with next steps to merge it?

2023-05-30 18:45 UTC, closed without merging