Infra test changes
delta-io/delta pull request #2274
Opened 2023-11-08 17:42 UTC by scottsand-db

2023-11-15 18:41 UTC, allisonport-db approved these changes
LGTM

2023-11-15 18:56 UTC, vkorukanti requested changes

2023-11-15 18:56 UTC, vkorukanti commented on spark/src/main/scala/org/apache/spark/sql/delta/DeltaThrowable.scala
> +trait DeltaThrowable extends SparkThrowable { // some change 4
what is this?

2026-07-27 18:12 UTC, foss-contributor commented
@scottsand-db, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:18 UTC, closed without merging