Test 01
delta-io/delta pull request #2345
Opened 2023-11-30 17:22 UTC by scottsand-db

2023-11-30 17:31 UTC, allisonport-db approved these changes
Dope!

2023-11-30 17:33 UTC, lzlfred requested changes
not intended ?

2023-11-30 17:34 UTC, vkorukanti requested changes

2023-11-30 17:35 UTC, lzlfred requested changes
not intended ?

2023-11-30 17:53 UTC, zachschuermann requested changes
says i need comment

2023-11-30 18:07 UTC, allisonport-db requested changes
¯\_(ツ)_/¯

2026-07-27 18:12 UTC, foss-contributor commented
@scottsand-db, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:18 UTC, closed without merging