Test 01 (again) (only requests for changes) (please, oh please, don't approve it)
delta-io/delta pull request #2349
Opened 2023-11-30 18:34 UTC by scottsand-db

2023-11-30 18:37 UTC, zachschuermann requested changes
req

2023-11-30 18:38 UTC, lzlfred requested changes
req

2023-11-30 18:53 UTC, allisonport-db requested changes
:(

2026-07-27 18:13 UTC, foss-contributor commented
@scottsand-db, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:31 UTC, closed without merging