[Kernel][Expressions] Adds the IS_NULL expressions
delta-io/delta pull request #2651
Opened 2024-02-17 16:56 UTC by tlm365

#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

## Description
Resolve #2632. Adds the IS NULL expressions.

## How was this patch tested?
Adds unit test.

2024-02-18 22:37 UTC, vkorukanti requested changes
Looks great. 

Minor comment. Ready to merge once resolved.

2024-02-18 22:37 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java
> + *    <li>Since version: 3.1.0</li>
```suggestion
 *    <li>Since version: 3.2.0</li>
```

2024-02-18 22:37 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java
> + *    <li>Since version: 3.1.0</li>
This will go in next release version 3.2.0

2024-02-18 22:37 UTC, vkorukanti commented on kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
> +            Expression child = visit(predicate.getChildren().get(0)).expression;
```suggestion
            Expression child = visit(getUnaryChild(predicate)).expression;
```

2024-02-18 22:37 UTC, vkorukanti commented on kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/expressions/DefaultExpressionEvaluator.java
> +            ColumnVector childResult = visit(childAt(predicate, 0));
```suggestion
            ColumnVector childResult = visit(getUnaryChild(predicate));
```

2024-02-19 08:08 UTC, tlm365 commented
> Looks great.
> 
> Minor comment. Ready to merge once resolved.

@vkorukanti TYSM, I have resolved it.

2024-02-19 18:52 UTC, vkorukanti approved these changes

2024-02-19 19:34 UTC, merged