Scan files support tags filed.
delta-io/delta pull request #3119
Opened 2024-05-20 16:34 UTC by horizonzy

Now, the file scan result didn't contain a tags field. In our case, we define some custom properties in the tags filed, so we want to filter the AddFile according to the custom tags.

2024-05-20 16:34 UTC, horizonzy commented
@vkorukanti /cc

2024-05-20 18:52 UTC, vkorukanti requested changes
@horizonzy Thanks for the PR. One change request: always reads the `tags`,  so that the `Scan.getScanFiles()` always has the `tags` for each returned row. That should simplify this PR.

And also please update the `Scan.getScanFiles()` javadoc to include the new columns `tags`.

2024-05-20 18:52 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/ScanImpl.java
> -        return getScanFiles(engine, false);
Let's make reading the tags by default. Most cases the contents are empty, so shouldn't add extra overhead for reads.

2024-05-21 03:07 UTC, horizonzy commented
> @horizonzy Thanks for the PR. One change request: always reads the `tags`, so that the `Scan.getScanFiles()` always has the `tags` for each returned row. That should simplify this PR.
> 
> And also please update the `Scan.getScanFiles()` javadoc to include the new columns `tags`.

The method `Scan.getScanFiles()` doc links the SCAN_FILE_SCHEMA_WITH_STATS, I think we needn't mark the changes for the method. We can mark the change in the next release note.

2024-05-21 15:55 UTC, vkorukanti requested changes
Looks good.

Fews things:
* Please update the javadoc [here](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/Scan.java#L68) for `Scan.getScanFileInfo`. Basically it contains the schema of the scan file rows returned. You can just add
```
<li>name: {@code tags}, type: {@code map(string, string)}, description: Map containing metadata about the scan file.</li>
```

* Remove `stats` and `tags` from the `FileStatus`. They don't belong there. I commented on the PR about the alternative.

* A simple test. You can add a Delta table which contains tags for AddFile. And verify that `Scan.getScanFiles()` returns the tags. You can add this to `ScanSuite.scala`. 

Let me know if you any questions.

2024-05-21 15:55 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
> +        .add("tags", new MapType(StringType.STRING, StringType.STRING, true), true);
```suggestion
        .add("tags",
                new MapType(StringType.STRING, StringType.STRING, true /* valueContainsNull */),
                true /* nullable */);
```

2024-05-21 15:55 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/utils/FileStatus.java
> +
`FileStatus` is a public API and we can't have these fields in `FileStatus`. If you need an object with file info, stats, and tags, you can create one in your connector and write a utility method similar to the `InternalScanFileUtils.getAddFileStatus`.

2024-05-21 18:55 UTC, vkorukanti approved these changes

2024-05-21 18:56 UTC, merged