[Kernel] Write a new inCommitTimestamp in CommitInfo on every commit
delta-io/delta pull request #3188
Opened 2024-06-01 00:21 UTC by EstherBear

Write a non-monotonic timestamp in a new inCommitTimestamp field in CommitInfo on every commit.

#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

## Description

## How was this patch tested?

## Does this PR introduce _any_ user-facing changes?

2024-06-01 01:16 UTC, dhruvarya-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +                generateInCommitTimestampForFirstCommitAttempt(
Can you flag this change behind this table property: https://github.com/delta-io/delta/blob/59f8c64c2a2bc49877e8e19913c9249f9f337028/spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala#L765 ?

2024-06-01 01:16 UTC, dhruvarya-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/Snapshot.java
> +    Path getLogPath();
This is for tests only right? If so, you can just infer the `logPath` from the `tablePath` here (https://github.com/delta-io/delta/pull/3188/files#diff-566027baa96501b600cdc402655e8b787c2e04c4428eaf432294ee9dee6a7002R53) and avoid this change.

2024-06-03 23:29 UTC, dhruvarya-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/CommitInfo.java
> +            .add("inCommitTimestamp", LongType.LONG, true /* nullable */)
Please describe this field above L32.

2024-06-03 23:29 UTC, dhruvarya-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +    public static final TableConfig<Boolean> IN_COMMIT_TIMESTAMPS_ENABLED = new TableConfig<>(
Add a description of this flag.

2024-06-03 23:29 UTC, dhruvarya-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/Snapshot.java
> +    Metadata getMetadata();
Add docstring

2024-06-03 23:29 UTC, dhruvarya-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
> +      assert(!TableConfig.IN_COMMIT_TIMESTAMPS_ENABLED.fromMetadata(ver0Snapshot.getMetadata))
Can you make `getInCommitTimestamp` return Option[Long] and add another assertion here which ensures that ICT is None for commit 0?

2024-06-05 01:07 UTC, dhruvarya-db commented
@EstherBear can you please update the PR description such it follows the provided template?

2024-06-05 05:09 UTC, vkorukanti requested changes
Thank you for the PR!

Couple of qn:
1) Why is the ICT not monotonically increasing? Should we read the last commit info first, before attempting to generate the next ICT?
2) I didn't understand the test. We seems to be testing the table created using the Spark and not Kernel. Wondering what I am missing here.

2024-06-05 05:09 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    private Optional<Long> generateInCommitTimestampForFirstCommitAttempt(long currentTimestamp) {
Why is this a first commit attempt? Isn't it used for every commit?

2024-06-05 05:09 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +        long commitAttemptStartTime = System.currentTimeMillis();
why are we not reading the existing timestamp, so that the next commit timestamp is monotonically increasing?

2024-06-05 05:09 UTC, vkorukanti commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/InCommitTimestampSuite.scala
> +      createTableWithInCommitTimestampsEnabled(tablePath, true)
what are we testing here? this method creates the table with Spark.

2026-05-05 00:00 UTC, felipepessoto commented
Duplicated of https://github.com/delta-io/delta/pull/3282?

2026-07-27 21:32 UTC, foss-contributor commented
@EstherBear, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:46 UTC, closed without merging