[Kernel][Writes] Add support for writing data file stats
delta-io/delta pull request #3342
Opened 2024-07-08 17:39 UTC by raveeram-db

#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

## Description
Serializes stats to the data file on writes. 

## How was this patch tested?
Unit tests. 

## Does this PR introduce _any_ user-facing changes?
No

2024-08-05 06:45 UTC, raveeram-db commented
Will fix the tests.

2025-02-24 19:08 UTC, vkorukanti requested changes
Looks great!

Also it would be good if we can add an integration tests and make sure it is readable/usable in Kernel/Delta-Spark read tests.

2025-02-24 19:08 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      Column colPath = parentColPath.append(field.getName());
you can actually just mantain the path as a list and we can avoid the extra API on the `Column`

2025-02-24 19:08 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +        if (value != null) {
we may want to type check the Literal matches the data type to make sure to not write incorrect stats

2025-02-24 19:08 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/utils/JsonUtil.java
> +  public interface ToJson {
what is this interface for?

2025-02-24 19:08 UTC, vkorukanti commented on kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/DataFileStatisticsSuite.scala
> +      new Column("DoubleType") -> Literal.ofDouble(0.1),
please add all variants of the double: NaN, infinity. Same for float.

2025-02-24 19:53 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Column.java
> +  public Column append(String name) {
thanks, makes sense, updated to `appendNestedField`

2025-02-24 19:56 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    return TransactionStateRow.getLogicalSchema(engine, transactionState).fields().stream()
Just the top level columns, looking at the code, `fields` does seem to only traverse top level columns but i'll double check

2025-02-24 19:58 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      Column colPath = parentColPath.append(field.getName());
Yeah felt like that'd just be extra state to maintain and tradeoff readability a bit; the API could come in handy in other places as well perhaps. Lmk if you feel strongly and I can update

2025-02-26 00:09 UTC, allisonport-db reviewed
Haven't finished looking but submitting pending comments for now. JSON generation looks very clean!

So far mainly have questions around what kind of validation should we do to prevent bad statistics input from the connector?

Also +1 on integration tests, let's make sure Kernel & Spark can read these statistics and can use them to skip files

2025-02-26 00:10 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson() {
should we take in the expected schema here (from the txn that is generating the stats) and make sure it's the same? or any other ideas on if/where we should validate the `dataSchema`?

2025-02-26 17:53 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +                    String.valueOf(DataSkippingUtils.DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS)));
Hey @allisonport-db -- this is a static method. I believe we do have to use the TxnStateRow? Metadata isn't an input to the method.

Let me know if I'm missing something!

2025-02-26 18:11 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +                    String.valueOf(DataSkippingUtils.DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS)));
oops! ignore me haha :)

2025-02-26 18:19 UTC, scottsand-db reviewed
Looks great! Left only a few minor comments / questions.

Seems like we need some tests for `DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS` and, in particular, need to test + document the expected behavior for how nested columns impact the total column count.

2025-02-26 18:19 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      Column parentColPath,
nit: `parentCol`

2025-02-26 18:19 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson() {
It would be nice to include a method docs comment explaining what the serialized JSON will look like? This will help give an intuition as to what the method is doing.

2025-02-26 18:19 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      StructType dataSchema,
can we include any nullability checks?

2025-02-26 18:19 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +   * nullCounts). Full deserialization support for all statistics will be added in a future update.
Question: This means we do not really have data skipping, right? cc @allisonport-db to confirm my understanding?

2025-02-26 18:30 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public DataFileStatistics(
I think at a high-level we should define what we expect connectors to input here, and what rules we expect them to follow in order to write correct and useful statistics. And then we should enforce them :) We should treat this constructor as a public API as connectors will need to create these. I think I left general comments all over to this nature but this is kind of the gist of it.

2025-02-26 18:30 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +    this.minValues = Collections.unmodifiableMap(minValues);
Also `requireNonNull` for all of these? Maybe depends on what we decide are the expectations for connectors. Maybe we should have another constructor that only takes in `numRecords`?

2025-02-26 18:30 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +    this.minValues = Collections.unmodifiableMap(minValues);
> I think we only store stats for certain column data types right? should we validate that?

Ah I see we throw an error upon writing. I guess we should decide whether that's a good place to do it or if we should do some overall validation upon construction

2025-02-26 18:30 UTC, allisonport-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/DataFileStatisticsSuite.scala
> +      new Column("DoubleType") -> Literal.ofDouble(0.1),
I think when I added `DefaultJsonHandlerSuite` I was pretty thorough about edge cases for various types if it helps the tests are here https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/engine/DefaultJsonHandlerSuite.scala

2025-02-26 18:32 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +   * nullCounts). Full deserialization support for all statistics will be added in a future update.
Haha I commented a similar thing here. From looking at the code, it seems like this is only used by row tracking during writes to get the numRecords. Our data skipping uses the JsonHandler to parse JSON in a completely different code path. I think this is a fine utility for that specific use case (as it's for 1 add-file, and not over batches) but we should document this better to be clear what it is and what it isn't used for.

2025-02-26 19:48 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +   * nullCounts). Full deserialization support for all statistics will be added in a future update.
Thank you both, that's right, the data skipping path goes through the JsonHandler and this is only used by row tracking and checked with @qiyuandong-db - they only care about the `numRecords` field in `AddFile` for now. I'll create a task to also add support for deserializing stats but given we won't have the dataSchema here, we'll have to be mindful of safety and all.

2025-02-26 19:57 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +   * nullCounts). Full deserialization support for all statistics will be added in a future update.
I think maybe we don't need to do that (yet at least)? Is there any requirement for the other stats during writes?

Maybe we can just make this a smaller scoped utility that only gets the numRecords from a stats json?

2025-02-26 20:04 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +   * nullCounts). Full deserialization support for all statistics will be added in a future update.
None yet, yeah, i'll move this out to a Utils class to avoid confusion

2025-02-26 20:49 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    return TransactionStateRow.getLogicalSchema(engine, transactionState).fields().stream()
I spoke with Rahul Mahadev. Nested fields _should_ count towards the total columnd included. (this is what delta-spark does)

e.g. Suppose I have a table `c1: INT, c2: STRUCT with nested columns sub1, ..., sub33, c2: INT`

Then if I have 32 columns indexed for stats collection, only `c1`, `c2.sub1`, ..., `c2.sub31` will be included.

`c2.sub32, c2.sub33, c3` will be excluded from stats collection.

2025-02-27 01:36 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    return TransactionStateRow.getLogicalSchema(engine, transactionState).fields().stream()
Ack, yup thanks Scott. I'll update

2025-03-04 19:41 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeNumber(((Number) value).doubleValue());
Updated.

2025-03-04 19:41 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/utils/JsonUtil.java
> +/*
Yup, merged the two classes.

2025-03-04 19:42 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/utils/JsonUtil.java
> +  public interface ToJson {
Ah just to allow for the JsonWriter and Jackson to be decoupled in all call sites (should we ever choose to remove it, although I hope not :))

2025-03-05 23:40 UTC, raveeram-db commented
> Looks great! Left only a few minor comments / questions.
> 
> Seems like we need some tests for `DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS` and, in particular, need to test + document the expected behavior for how nested columns impact the total column count.

Thanks @scottsand-db , added a test and a clarifying comment for the same

2025-03-05 23:40 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson() {
Thanks added.

2025-03-05 23:40 UTC, raveeram-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/internal/util/DataFileStatisticsSuite.scala
> +class DataFileStatisticsSuite extends AnyFunSuite with Matchers {
Makes sense, added.

2025-03-06 01:35 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson() {
Updated the flow here to ensure that the right schema flows through the kernel.

2025-03-06 17:38 UTC, scottsand-db requested changes
Looks great! Left some minor comments -- after those are resolved, LGTM

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +          "needs to be a positive integer.",
I think we should follow exactly what delta-spark does?

https://github.com/delta-io/delta/blob/50aa783c64c7b727e13ad744f82cebd705b99e01/spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala#L573

i.e. value needs to be >= -1. -1 means collect for all columns.

In general, I think we should copy more context from the delta-spark config comments, and also mention the relationship with nested fields?

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +        TransactionStateRow.getPartitionColumnsList(transactionState).stream()
nit: can we just do `new HashSet<>(TransactionStateRow.getPartitionColumnsList(transactionState))` ? it avoids the overhead of all the stream creation

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java
> +      Column currentColumn = null;
nit: you can do `final Column currentColumn;` // do can avoid assigning to null and then re-assigning later

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/StatsUtils.java
> +      root = new ObjectMapper().readTree(json);
It's actually better to save ObjectMapper to a static final field once, than to keep recreating new instances of it each invocation

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public static final int MICROSECONDS_PER_SECOND = 1_000_000;
nit (sorry) -- static variables before member variables

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
> +      StructType tableSchema,
logial schema? physial schema?

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
> +        stat -> fieldMap.put(FULL_SCHEMA.indexOf("stats"), stat.serializeAsJson(tableSchema)));
serializeAsJson takes the `dataSchema` but here we are passing in the `tableSchema` -- just calling this out. I think this is fine?

2025-03-06 17:38 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +/** Statistics about data file in a Delta Lake table. */
I still think it is worth calling out a bit more how this class is used?

`Notably, this class it NOT used during data skipping -- that operations on columnar batches (or something, etc etc etc). Instead, this class is used for XXX YYY`

2025-03-06 18:13 UTC, vkorukanti reviewed
One major comment handling the physical column names when column mapping is enabled.

2025-03-06 18:13 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +          "needs to be a positive integer.",
If that is the defined behavior, lets change that. Should be relatively easy to do that in the current PR or follow up PR is fine too.

2025-03-06 18:13 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
> +  public static final int DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS = 32;
remove this?

2025-03-06 18:13 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/StatsUtils.java
> +      root = new ObjectMapper().readTree(json);
+1

2025-03-06 18:13 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson(StructType dataSchema) {
We should take the physical schema as the input. The data files get the physical data and collects stats of the written physical column.

2025-03-06 18:13 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    return SchemaUtils.collectLeafColumns(
We should get the physical column names and not the logical columns names. The data that is being written to Parquet files has the physical schema and the stats are collected on the physical columns.

2025-03-06 18:42 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/AddFile.java
> +      StructType tableSchema,
yeah I think we need to clean-up some of this terminology and settle on one. I see different variants of table, data, physical and logicalSchema being used. I'll have a look and if it's a bigger change, i'll fix it in a follow-up PR

2025-03-06 18:43 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/StatsUtils.java
> +      root = new ObjectMapper().readTree(json);
Yup makes sense, previous util I refactored, i'll fix it.

2025-03-06 19:02 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +          "needs to be a positive integer.",
Good point and makes sense. Will update.

2025-03-07 17:09 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +          "needs to be a positive integer.",
Fix and added a test, thanks folks.

2025-03-10 17:11 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public String serializeAsJson(StructType dataSchema) {
makes sense, updated to take the physical schema as input.

2025-03-10 22:41 UTC, vkorukanti requested changes
Looks great overall! Just few last minor comments.

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
> +                  TransactionStateRow.getPhysicalSchema(transactionState),
can this be created at line #210 and we can avoid the cost to construct physical schema for every add file row.

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/skipping/DataSkippingUtils.java
> +  public static final int DEFAULT_DATA_SKIPPING_NUM_INDEXED_COLS = 32;
we still need these?

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +  public DataFileStatistics(
one thing to emphasize in the docs is the stats are for the data written in the file and column names here are the same as the ones used in the Parquet file.

Later on when we move to id based stats, we can update it.

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +    this.minValues = Collections.unmodifiableMap(minValues);
```suggestion
    this.minValues = Collections.unmodifiableMap(requireNonNull(minValues, "minValues is null"));
```

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +    this.minValues = Collections.unmodifiableMap(minValues);
same for others

2025-03-10 22:41 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeString((String) value);
do we need to truncate the string length? What does the delta-spark do?

2025-03-10 22:44 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/Transaction.java
> +                  TransactionStateRow.getPhysicalSchema(transactionState),
Yup that makes sense. Will update

2025-03-11 16:53 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeString((String) value);
Looks like the truncation happens during stats collection in `delta-spark` and perhaps does make sense for the Kernel to leave that to the connectors/engines to define.

2025-03-11 17:10 UTC, vkorukanti approved these changes
LGTM.

Couple of comments on the string/binary serialization to check it conforms to the spec (or Delta-Spark behavior)

2025-03-11 17:10 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeString((String) value);
Does Delta protocol specify any requirements? Also do we need to escape any special characters in the value?

2025-03-11 17:10 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeString(new String((byte[]) value, StandardCharsets.UTF_8));
does Delta-Spark do the same? Convert as UTF-8 string?

2025-03-11 17:22 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/statistics/DataFileStatistics.java
> +      generator.writeString((String) value);
That's handled by Jackson serialization and delta-spark also appears to follow the same

2025-03-11 18:46 UTC, merged

2025-03-12 02:15 UTC, allisonport-db reviewed
Minor comments/questions

2025-03-12 02:15 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    // numIndexedCols limit (not Map/ArrayTypes - they're not stats compatible types).
It seems like we do include the complex type columns in this list right? I don't see anywhere that we exclude them

2025-03-12 02:15 UTC, allisonport-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
> +  Seq(0, -1).foreach { numIndexedCols =>
I feel like we should also test something like 4 here? To make sure we do in fact limit (and nested columns do count toward that limit)

2025-03-12 02:15 UTC, allisonport-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
> +  Seq(0, -1).foreach { numIndexedCols =>
Also should we test that partition columns are excluded?

2025-03-12 02:15 UTC, allisonport-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
> +  test("insert into table - write stats and validate they can be read by Spark ") {
How does this validate that spark can read the stats? I might be missing something but I don't think we use data skipping with spark over the table?

2025-03-12 02:15 UTC, allisonport-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
> +  test("insert into table - write stats and validate they can be read by Spark ") {
It would also be nice if we could (easily) validate this for all data types. I'm wondering if we can just copy over a spark test suite that tests data skipping - but generate the base table with Kernel instead?

Not sure how easy/difficult this might be to do; if it's simple it'd be great test coverage

2025-03-12 02:37 UTC, raveeram-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
> +  test("insert into table - write stats and validate they can be read by Spark ") {
Ah `verifyWrittenContent` does a `SELECT * from..` on the table which should also validate that the stats get parsed at least. That's a great idea though and let me see if we can add one similar to that for all types

2025-03-12 02:37 UTC, raveeram-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/TransactionSuite.scala
> +  Seq(0, -1).foreach { numIndexedCols =>
Yup that makes sense, I did add one with 3 but didn't push the changes, will update this in a follow up PR. Thanks Alli.

2025-03-12 02:40 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/StatsUtils.java
> +  public static Optional<DataFileStatistics> deserializeFromJson(String json) {
Makes sense, will update

2025-03-12 02:47 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionImpl.java
> +    // numIndexedCols limit (not Map/ArrayTypes - they're not stats compatible types).
Yeah I think this comment needs to be clarified, meant to say these are stats ineligible types but do count towards the limit (Delta-Spark atleast appears to do that)

2025-03-12 02:48 UTC, raveeram-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/TableConfig.java
> +   * would be a, b.c, and b.d. Map and array types are not supported for statistics collection.
Ah no, we do not (verified with Delta-Spark as well)

2025-03-12 16:51 UTC, allisonport-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
> +  test("insert into table - write stats and validate they can be read by Spark ") {
I don't actually know, but I have an inkling that spark might only lazily parse those stats if we do data skipping. So I'm not confident the stats are parsed from the select * query without a filter on stats columns...

2025-03-12 17:23 UTC, raveeram-db commented on kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/DeltaTableWritesSuite.scala
> +  test("insert into table - write stats and validate they can be read by Spark ") {
Yeah good point, thanks, will add a few more targeted queries/tests that validate data skipping specifically.