[Test] Upgrade Spark version to use 3.5.2 RC2
delta-io/delta pull request #3417
Opened 2024-07-24 05:52 UTC by vkorukanti

Test only

2024-07-25 13:07 UTC, yaooqinn commented on build.sbt
> +    resolvers += "Apache Spark 3.5.2 (RC2) Staging" at "https://repository.apache.org/content/repositories/orgapachespark-1458/",
```suggestion
    resolvers += "Apache Spark 3.5.2 (RC3) Staging" at "https://repository.apache.org/content/repositories/orgapachespark-1459/",
```

2024-07-25 13:08 UTC, yaooqinn commented
Hi @vkorukanti. 
Spark 3.5.2 (RC3) is polling. Please help Spark community to verify it.

Thanks,
Kent Yao

2024-08-08 15:58 UTC, vkorukanti commented on .github/workflows/spark_test.yaml
> +          pipenv run pip install https://dist.apache.org/repos/dist/dev/spark/v3.5.2-rc3-bin/pyspark-3.5.2.tar.gz
```suggestion
          pipenv run pip install https://dist.apache.org/repos/dist/dev/spark/v3.5.2-rc5-bin/pyspark-3.5.2.tar.gz
```

2024-08-08 15:58 UTC, vkorukanti commented on build.sbt
> +    resolvers += "Apache Spark 3.5.2 (RC3) Staging" at "https://repository.apache.org/content/repositories/orgapachespark-1459/",
```suggestion
    resolvers += "Apache Spark 3.5.2 (RC5) Staging" at "https://repository.apache.org/content/repositories/orgapachespark-1462/",
```

2024-08-13 17:16 UTC, scottsand-db approved these changes

2024-08-13 17:17 UTC, allisonport-db requested changes
Can you also update setup.py and anywhere else that is 3.5.0?

2024-08-13 18:41 UTC, allisonport-db approved these changes

2024-08-13 20:36 UTC, vkorukanti commented
The Spark master failure is unrelated to this PR.

2024-08-13 20:37 UTC, merged