[Kernel] Ignore non-conforming commit files in Delta log directory
delta-io/delta pull request #3552
Opened 2024-08-13 23:59 UTC by vkorukanti

## Description
Support for coordinated commit introduced an issue where a Delta file in `_delta_log` that doesn't conform to the expected file name format (`%020d.json`) is considered part of the Delta history. 

We use the following method to test whether a file is a `commit` file.

Before coordinated commit support:

```
  public static boolean isCommitFile(String filePath) {
    String fileName = ..
    return Pattern.compile("\\d+\\.json").matcher(fileName).matches();
  }
```

After the coordinated commit support:
```
  public static boolean isCommitFile(String filePath) {
    String fileName = ..
    return Pattern.compile("\\d+\\.json").matcher(fileName).matches() || // backfilled commit file
        Pattern.compile("(\\d+)\\.([^\\.]+)\\.json").matcher(fileName).matches() // un-backfilled commit file
  }
```

For example, if the `_delta_log` has a file with name `0000x.uuid.json`, it will be considered to be part of the delta file, but it is not. The commit files of format `%20d.uuid.json` are considered part of the table history only if the parent directory name is `_commit`.

Update the above method as follows (this is in line with the Delta-Spark)

```
  public static boolean isCommitFile(String filePath) {
    String fileName = ...
    String parentDirName = ...
    return Pattern.compile("\\d+\\.json").matcher(fileName).matches() || // backfilled commit file
        (parentDirName == "_commit" &&
            Pattern.compile("(\\d+)\\.([^\\.]+)\\.json").matcher(fileName).matches()) // un-backfilled commit file
  }
```

## How was this patch tested?
Unit test that reproes the issue without the fix

2024-08-14 00:00 UTC, vkorukanti commented on kernel/kernel-api/src/test/scala/io/delta/kernel/internal/SnapshotManagerSuite.scala
> +      expectedVersion = 14,
without the fix, this returns the latest snapshot version as 19.

2024-08-15 16:05 UTC, prakharjain09 commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/FileNames.java
> +    String fileParentName = filePath.getParent().getName();
[nit] Can we fetch the fileParentName only when it is needed? These Path/URI operations are slow and may cause slowness when applied on large number of objects.

    if (DELTA_FILE_PATTERN.matcher(fileName).matches()) {
      return true
    } else {
      String fileParentName = filePath.getParent().getName();
      return COMMIT_SUBDIR.equals(fileParentName)
        && UUID_DELTA_FILE_REGEX.matcher(fileName).matches());
    }

2024-08-15 16:05 UTC, prakharjain09 approved these changes

2024-08-16 01:14 UTC, allisonport-db approved these changes

2024-08-16 01:17 UTC, allisonport-db requested changes
A bunch of tests are failing as not a commit file?

2024-08-20 23:09 UTC, vkorukanti commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/DeltaLogFile.java
> +    if (FileNames.isCommitFile(filePath)) {
create https://github.com/delta-io/delta/issues/3586 to unify these utility APIs

2026-07-28 16:37 UTC, foss-contributor commented
@vkorukanti, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-04 16:45 UTC, closed without merging