Metrics 3
delta-io/delta pull request #3904
Opened 2024-11-26 19:44 UTC by allisonport-db

#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

## Description

## How was this patch tested?

## Does this PR introduce _any_ user-facing changes?

2024-12-04 19:15 UTC, scottsand-db requested changes
Looks great! 2 minor comments

2024-12-04 19:15 UTC, scottsand-db commented on kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/LoggingMetricsReporter.java
> +            "SnapshotReport = %s",
aren't we supposed to use {} instead of %s with `logger.info`?

2024-12-04 19:15 UTC, scottsand-db commented on kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/engine/LoggingMetricsReporter.java
> +  private static final Logger logger = LoggerFactory.getLogger(SnapshotManager.class);
`LoggingMetricsReporter.class`

2025-01-06 18:21 UTC, scottsand-db approved these changes
LGTM with two minor comments!

2025-01-06 18:21 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
Seems like we would have to do this for every type of report, right?

Any way to avoid that? (Since they would all just call `OBJECT_MAPPER.writeValueAsString(inputVariable)`

Could we just take in a DeltaOperationReport?

2025-01-06 18:21 UTC, scottsand-db commented on kernel/kernel-api/src/test/scala/io/delta/kernel/internal/metrics/MetricsReportSerializerSuite.scala
> +  def testSnapshotReport(snapshotReport: SnapshotReport): Unit = {
nit: private?

2025-01-07 03:24 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
yeah I wasn't sure about this because I also think there's a use-case where you are only serializing a specific report type. maybe we can have both `serializeSnapshotReport` and `serializeDeltaOperationReport`

But then I need to make `DeltaOperationReport` serializable (which currently I did not). What do you think?

2025-01-08 21:29 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
Every report we create will implement DeltaOperationReport, right?

And every report we create we will by default log in with our default engine, right?

Then it seems fair that DeltaOperationReport be serializable 👍

2025-01-08 23:42 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
Hmm I have some thoughts that I haven't fully fleshed out.

Every operation-type report we create will implement DeltaOperationReport, possibly not every report. But yes we probably plan to log all report types in our default engine (I can't think of a reason not to currently). But that would argue that we should make `MetricsReport` serializable....

If we add a new report type i.e. `XXReport extends DeltaOperationReport` but don't make it serializable, it will still be serialized but will be missing additional information in XXReport.

Do we ever expect an report that only extends DeltaOperationReport? Maybe we just want to report that an operation occurred or success vs failure?

Need to verify that if both DeltaOperationReport and SnapshotReport are serializable jackson will use the lowest ancestor.

2025-01-08 23:43 UTC, allisonport-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
I wonder if this is something we can flesh out later? These are all internal APIs and for now, I think, making sure the main report types are serializable is enough.

2025-01-08 23:44 UTC, scottsand-db commented on kernel/kernel-api/src/main/java/io/delta/kernel/internal/metrics/MetricsReportSerializers.java
> +  public static String serializeSnapshotReport(SnapshotReport snapshotReport)
> I wonder if this is something we can flesh out later?

Yup! SGTM!

2025-01-09 02:33 UTC, merged