[SC-77396] Block confusing SQL CREATE TABLE behavior
delta-io/delta pull request #688
Opened 2021-06-01 21:02 UTC by FX196

Added logic and unit tests to block queries like ``CREATE TABLE delta.`/foo` USING delta LOCATION "/bar"`` where ambiguous paths are supplied.
Users can allow such queries by setting the `DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS` flag to true, in which case the `USING delta LOCATION "/bar"` statement will be ignored.

2021-06-02 18:02 UTC, Yaohua628 commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala
> +  test("block table creation with ambiguous delta paths") {
nit: maybe you could put those 2 tests into one block:
```
Seq(true, false).foreach { enabled =>
  withSQLConf(DeltaSQLConf.DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key -> enabled.toString)
```
And then a separate one liner test to check DeltaSQLConf.DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key is set to false by default.
```
assert(!spark.conf.get(DeltaSQLConf.DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS))
```

2021-06-02 18:02 UTC, zsxwing requested changes
Thanks! Most of my comment are code style comments. Could you also add a test to test the behavior when two paths are the same?

2021-06-02 18:02 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
> +             |Delta was unintentionally allowing CREATE TABLE queries with both 'delta.`path`'
Delta was unintentionally allowing CREATE TABLE queries with both 'delta.`path`' and `LOCATION path` clauses. In the new version, we will raise an error for this case. This flag is added to allow users to skip the check. when it's set to true and there are two paths in CREATE TABLE, the `LOCATION path` clause will be ignored like what the old version does.

2021-06-02 21:07 UTC, FX196 commented
Style issues addressed and added checks for the default value and the case where two paths are the same.

2021-06-03 01:32 UTC, zsxwing requested changes

2021-06-03 01:32 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
> +         |DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key to true to skip this check.
`DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key` -> `${DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key}`

2021-06-03 01:32 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/sql/delta/DeltaErrors.scala
> +  def ambiguousPathsInCreateTableException(identPath: String, propertiesPath: String): Throwable = {
nit: `identPath` -> `identifier`, `propertiesPath` -> `location`.

2021-06-03 01:32 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala
> +             |and 'USING delta LOCATION path' clauses. In the new version, we will raise an error
nit: `USING delta` is redundant.

2021-06-03 01:32 UTC, zsxwing commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala
> +  test("allow ambiguous delta paths with legacy flag") {
forgot to remove?

2021-06-03 01:32 UTC, zsxwing commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala
> +      withSQLConf(DeltaSQLConf.DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS.key -> "true") {
nit: this should be removed

2021-06-03 01:32 UTC, zsxwing commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaDDLSuite.scala
> +    assert(!spark.conf.get(DeltaSQLConf.DELTA_LEGACY_ALLOW_AMBIGUOUS_PATHS))
we don't need this. The test that verifies the behavior without setting the flag has tested the default value.

2021-06-03 18:29 UTC, zsxwing approved these changes
LGTM. Thanks!

2021-06-04 20:43 UTC, closed without merging

2021-06-04 20:43 UTC, FX196 commented
Imported