Issue #809: Fix Creating an external table options
delta-io/delta pull request #820
Opened 2021-11-01 09:17 UTC by nflucian

This PR fix metadata.configuration inconsistent between write into delta and create delta table. #809

2021-11-12 21:50 UTC, allisonport-db commented
Hi Lucian, thank you for contributing and submitting this PR. This is definitely a bug we want to fix and we are reviewing it now.

2021-11-17 08:17 UTC, zsxwing commented
Thanks for making the PR. `metadata.configuration` is supposed to store the table properties rather than options. Currently we forget to remove options from table properties [here](https://github.com/delta-io/delta/blob/d9e38771fe8130f5dc01fd8576173ac0247accd1/core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala#L206-L207).

Could you just change the above place to split table properties and options properly? Similar to https://github.com/delta-io/delta/blob/d9e38771fe8130f5dc01fd8576173ac0247accd1/core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala#L354-L368

2021-12-02 19:54 UTC, zsxwing requested changes

2021-12-02 19:54 UTC, zsxwing commented on core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala
> +        catalogProp.properties ++ deltaPrefix
This should also be added to `DeltaTableProperties`. We would like to be consistent in all places.

2021-12-20 07:59 UTC, zsxwing commented
Sorry for being late. Although the change looks good, I will need to take some time to think about the backward compatibility.

2022-05-04 18:33 UTC, zsxwing commented
Sorry for the delay. I'm currently working on adding a new test suite to check the existing behaviors in all APIs that we can set options.

2022-05-06 16:47 UTC, zsxwing commented
Just to give a update. @scottsand-db is working on adding tests for the following complicated test matrix to check what are the behaviors in all combinations (Unfortunately, we have too many ways to create/write a Delta table today and they are not sharing the same code path):

Two types of options:
- Options starting with `delta.`
- Options not starting with `delta.`

Two ways to refer a Delta table
- Path
- Table name

APIs to write a Delta table
- DataFrameWriter save/saveAsTable
- DataStreamWriter (streaming) start/table
- Dataset.writeStream
- DataFrameWriterV2 
- DeltaTable.create
- DeltaTable.replace
- DeltaTable.createOrReplace
- SQL
  - CREATE TABLE … USING DELTA TBLPROPERTIES(...) 
  - CREATE TABLE … USING DELTA OPTIONS(...)
  - CREATE TABLE … USING DELTA OPTIONS(...) TBLPROPERTIES()
  - REPLACE
  - CREATE OR REPLACE
  - CREATE TABLE … AS SELECT * FROM XXX

- Different table states:
  - Create a new table
  - Overwrite an existing table
  - Append to an existing table

We want to have these tests first so that we can make sure any new changes will be consistent in all of these cases.

And thanks a lot, @scottsand-db  for offering the help to do this.

2022-05-09 21:32 UTC, scottsand-db commented
Here is the test suite which shows all the different ways to write configs to a delta table.
https://github.com/delta-io/delta/pull/1120

2022-05-17 17:02 UTC, scottsand-db commented
@nflucian just FYI we are still working on merging #1120 first before this PR.

2022-05-20 20:46 UTC, scottsand-db commented
Hi @nflucian, https://github.com/delta-io/delta/pull/1120 has been merged. It adds a test suite that shows the status of all the different combinations of writing configs into delta.

Can you update your branch with master? Then, could you please run `build/sbt 'core/testOnly *DeltaWriteConfigsSuite' and double check that your changes solve the problem? Can you then please update the relevant comment tables (e.g. [here](https://github.com/delta-io/delta/blob/master/core/src/test/scala/org/apache/spark/sql/delta/DeltaWriteConfigsSuite.scala#L393-L445)) with the latest result.

Let me know if you have any questions?

2022-05-24 23:34 UTC, scottsand-db requested changes
Left some comments. There's also 3 other big changes this PR needs.
1. We should only write options that are prefixed with `delta`. BUT we also need to be able to read old tables that do have options that aren't prefixed with delta. (Backwards compatibility)
2. We need a feature flag, which when enabled rolls back to the previous (i.e. current) behaviour.
3. A unit test that tests this backwards compatibility. See [EvolvabilitySuite](https://github.com/delta-io/delta/blob/master/core/src/test/scala/org/apache/spark/sql/delta/EvolvabilitySuite.scala)

2022-05-24 23:34 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableProperties.scala
> +  private def deltaProperties(writeOptions: Map[String, String]): Map[String, String] = {
scaladoc. describe the input and the output

2022-05-24 23:34 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableProperties.scala
> +  private def deltaProperties(writeOptions: Map[String, String]): Map[String, String] = {
scaladoc. describe the input and the output

2022-05-24 23:34 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableProperties.scala
> +  private def split(properties: Map[String, String]): (Map[String, String], Map[String, String]) = {
scaladoc: describe the output. what are the tuples?

2022-05-24 23:34 UTC, scottsand-db commented on core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableProperties.scala
> +  private def split(properties: Map[String, String]): (Map[String, String], Map[String, String]) = {
scaladoc: describe the output. what are the tuples?

2022-05-24 23:34 UTC, scottsand-db commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
> +        "header"-> "true",
After syncing with @zsxwing , we've confirmed that we do not want to write properties that are not prefixed with `delta`. Thus, to be clear, we only want to write to table metadata those properties which start with `delta`.

2022-05-24 23:34 UTC, scottsand-db commented on core/src/test/scala/org/apache/spark/sql/delta/DeltaSuite.scala
> +        "header"-> "true",
After syncing with @zsxwing , we've confirmed that we do not want to write properties that are not prefixed with `delta`. Thus, to be clear, we only want to write to table metadata those properties which start with `delta`.

2026-07-27 17:32 UTC, foss-contributor commented
@nflucian, thank you for your contribution! This pull request has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this pull request or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

2026-08-03 21:13 UTC, closed without merging